### ISSUE TITLE
Low resolution satellite images

### ISSUE THREAD

**Issue by whisper-bye** [rogermm14/eonerf#4]
Using high-resolution satellite data is quite expensive. Is it possible to achieve an acceptable quality by utilizing low-resolution data, such as Sentinel-2?

**Comment by rogermm14** [comment]
Hi @whisper-bye 

The method is not specific for a given satellite, it only requires that all input images have the same spatial resolution and observe the same area. However, the resolution of the resulting DSM will be limited by the resolution of your input images.

I find that NeRF-based methods are mostly interesting for obtaining detailed 3D representations from multiple HR images. If you only have a few low resolution images you may want to try a traditional stereo reconstruction first.
